spring.application.name=Spring-AI

server.port=9091

spring.ai.openai.api-key=${OPENAI-API-KEY}
spring.ai.openai.chat.options.model=gpt-5-nano
spring.ai.openai.chat.options.temperature=0.3
spring.ai.openai.retry.max-attempts=3
spring.ai.openai.retry.backoff=2000
logging.level.org.springframework.ai=INFO
